mti:
  auth:
    type: TokenAuth
    auth_uri: https://PLACEHOLDER/realms/cadip/protocol/openid-connect/token
    token_type: json
    token_key: access_token
    refresh_token_key: refresh_token
    token_expiration_key: expires_in
    request_method: POST
    req_data:
      client_id: PLACEHOLDER
      client_secret: PLACEHOLDER
      grant_type: PLACEHOLDER
      username: PLACEHOLDER
      password: PLACEHOLDER
    credentials:
      empty: value
    headers:
      Content-Type: application/x-www-form-urlencoded
  products:
    S1_SAR_RAW:
      productType: RAW
      collection: Sentinel1

  search:
    type: ODataV4Search
    api_endpoint: '{{ $.Values.app.station.mti.endpoint }}/Files'
    need_auth: true
    results_entry: $.value
    metadata_mapping:
      id:
        - null
        - '$.Id'
      Name:
        - null
        - '$.Name'
      SessionIds:
        - null
        - '$.SessionId'
      SessionId:
        - null
        - '$.SessionId'
      Channel:
        - null
        - '$.Channel'
      BlockNumber:
        - null
        - '$.BlockNumber'
      FinalBlock:
        - null
        - '$.FinalBlock'
      PublicationDate:
        - null
        - '$.PublicationDate'
      EvictionDate:
        - null
        - '$.EvictionDate'
      Size:
        - null
        - '$.Size'
      Retransfer:
        - null
        - '$.Retransfer'
      StartPublicationDate:
        - null
        - $.PublicationDate
      StopPublicationDate:
        - null
        - $.PublicationDate
      href:
        - null
        - '{{ $.Values.app.station.mti.endpoint }}/Files({id})/$value'
      geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
      downloadLink: '{{ $.Values.app.station.mti.endpoint }}/Files({id})/$value'
      title: '$.Name'

    free_text_search_operations:
      $filter:
        union: ' OR '
        operations:
          and:
            - 'SessionId in ({SessionIds})'
            - 'SessionId eq {SessionId}'
            - PublicationDate gt {StartPublicationDate#to_iso_utc_datetime}
            - PublicationDate lt {StopPublicationDate#to_iso_utc_datetime}
            - PublicationDate eq {PublicationDate#to_iso_utc_datetime}
            - "Retransfer eq {Retransfer}"

    pagination:
      max_items_per_page: 100
      next_page_url_tpl: '{url}?{search}&$top={items_per_page}&$skip={skip}'
      total_items_nb_key_path: '$.total'

    sort:
      sort_by_tpl: '&$orderby={sort_param} {sort_order}'
      sort_param_mapping:
        datetime: PublicationDate
      sort_order_mapping:
        ascending: asc
        descending: desc
      max_sort_params: 1

  download:
    type: HTTPDownload
    base_uri: '{{ $.Values.app.station.mti.endpoint }}/Files'
    metadata_mapping:
      uid: '$.Id'
      downloadLink: '{{ $.Values.app.station.mti.endpoint }}/Files({uid})/$value'

mti_session:
  auth:
    type: TokenAuth
    auth_uri: https://PLACEHOLDER/realms/cadip/protocol/openid-connect/token
    token_type: json
    token_key: access_token
    refresh_token_key: refresh_token
    token_expiration_key: expires_in
    request_method: POST
    req_data:
      client_id: PLACEHOLDER
      client_secret: PLACEHOLDER
      grant_type: PLACEHOLDER
      username: PLACEHOLDER
      password: PLACEHOLDER
    credentials:
      empty: value
    headers:
      Content-Type: application/x-www-form-urlencoded
  products:
    S1_SAR_RAW:
      productType: RAW
      collection: Sentinel1
  search:
    type: ODataV4Search
    api_endpoint: '{{ $.Values.app.station.mti.endpoint }}/Sessions'
    need_auth: true
    results_entry: $.value
    metadata_mapping:
      id:
        - null
        - "$.Id"
      SessionIds:
        - null
        - "$.SessionId"
      SessionId:
        - null
        - "$.SessionId"
      Satellite:
        - null
        - "$.Satellite"
      NumChannels:
        - null
        - "$.NumChannels"
      PublicationDate:
        - null
        - "$.PublicationDate"
      platform:
        - null
        - "$.Satellite"
      platforms:
        - null
        - "$.Satellite"
      StationUnitId:
        - null
        - "$.StationUnitId"
      DownlinkOrbit:
        - null
        - "$.DownlinkOrbit"
      AcquisitionId:
        - null
        - "$.AcquisitionId"
      AntennaId:
        - null
        - "$.AntennaId"
      FrontEndId:
        - null
        - "$.FrontEndId"
      Retransfer:
        - null
        - "$.Retransfer"
      AntennaStatusOK:
        - null
        - "$.AntennaStatusOK"
      FrontEndStatusOK:
        - null
        - "$.FrontEndStatusOK"
      PlannedDataStart:
        - null
        - "$.PlannedDataStart"
      PlannedDataStop:
        - null
        - "$.PlannedDataStop"
      DownlinkStart:
        - null
        - "$.DownlinkStart"
      DownlinkStop:
        - null
        - "$.DownlinkStop"
      DownlinkStatusOK:
        - null
        - "$.DownlinkStatusOK"
      DeliveryPushOK:
        - null
        - "$.DeliveryPushOK"
      Files:
        - null
        - "$.Files"
      StartPublicationDate:
        - null
        - $.PublicationDate
      StopPublicationDate:
        - null
        - $.PublicationDate
      href:
        - null
        - '{{ $.Values.app.station.mti.endpoint }}/Files({id})/$value'
      geometry: "POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))"
      title: "$.Name"

    free_text_search_operations:
      $filter:
        union: " OR "
        wrapper: '{}'
        operations:
          and:
            - "SessionId in ({SessionIds})"
            - "SessionId eq {SessionId}"
            - "Satellite eq {platform}"
            - "Satellite in ({platforms})"
            - PublicationDate gt {StartPublicationDate#to_iso_utc_datetime}
            - PublicationDate lt {StopPublicationDate#to_iso_utc_datetime}
            - PublicationDate eq {PublicationDate#to_iso_utc_datetime}
            - Id eq '{id}'
            - DownlinkOrbit eq {DownlinkOrbit}
            - DownlinkStart eq {DownlinkStart}
            - DownlinkStop eq {DownlinkStop}
            - NumChannels eq {NumChannels}
            - AcquisitionId eq '{AcquisitionId}'
            - AntennaId eq '{AntennaId}'
            - StationUnitId eq '{StationUnitId}'
            - FrontEndId eq '{FrontEndId}'
            - PlannedDataStart eq {PlannedDataStart}
            - PlannedDataStop eq {PlannedDataStop}
            - Retransfer eq {Retransfer}
            - AntennaStatusOK eq {AntennaStatusOK}
            - FrontEndStatusOK eq {FrontEndStatusOK}
            - DownlinkStatusOK eq {DownlinkStatusOK}
            - DeliveryPushOK eq {DeliveryPushOK}
            - '{t_contains}'
            - '{t_intersects}'

    pagination:
      max_items_per_page: 100
      next_page_url_tpl: "{url}?{search}&$top={items_per_page}&$skip={skip}"
      total_items_nb_key_path: "$.total"

    sort:
      sort_by_tpl: '&$orderby={sort_param} {sort_order}'
      sort_param_mapping:
        id: SessionId
        start_datetime: DownlinkStart
        datetime: PublicationDate
        end_datetime: DownlinkStop
        published: PublicationDate
        platform: Satellite
        cadip:num_channels: NumChannels
        cadip:station_unit_id: StationUnitId
        sat:absolute_orbit: DownlinkOrbit
        cadip:acquisition_id: AcquisitionId
        cadip:antenna_id: AntennaId
        cadip:front_end_id: FrontEndId
        cadip:retransfer: Retransfer
        cadip:antenna_status_ok: AntennaStatusOK
        cadip:front_end_status_ok: FrontEndStatusOK
        cadip:planned_data_start: PlannedDataStart
        cadip:planned_data_stop: PlannedDataStop
        cadip:downlink_status_ok: DownlinkStatusOK
        cadip:delivery_push_ok: DeliveryPushOK
        startTimeFromAscendingNode: DownlinkStart
        completionTimeFromAscendingNode: DownlinkStop
        publicationDate: PublicationDate
      sort_order_mapping:
        ascending: asc
        descending: desc
      max_sort_params: 1

  download:
    type: HTTPDownload
    base_uri: '{{ $.Values.app.station.mti.endpoint }}/Sessions'
    metadata_mapping:
      uid: "$.Id"
      downloadLink: "{{ $.Values.app.station.mti.endpoint }}/Files({uid})/$value"
