# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE WAS AUTOMATICALLY CREATED FROM:
#  - rs-server/services/common/config/rs-server.template.yaml
#  - rs-server/resources/sync_config_files.py
# DON'T MODIFY IT DIRECTLY !

namespace: processing
app:
  stations:
    adgs:
      service:
        name: auxip
        url: http://mockup-station-adgs.processing.svc.cluster.local:8080
      domain: mockup-station-adgs.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-adgs.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
      trusteddomains:
      - trusted.domain1.eu
      - trusted.domain2.eu
    adgs2:
      service:
        name: auxip
        url: http://mockup-station-adgs2.processing.svc.cluster.local:8080
      domain: mockup-station-adgs2.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-adgs2.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
    cadip:
      service:
        name: cadip
        url: http://mockup-station-cadip-cadip.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-cadip.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-cadip.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: null
    ins:
      service:
        name: cadip
        url: http://mockup-station-cadip-ins.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-ins.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-ins.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: null
    mps:
      service:
        name: cadip
        url: http://mockup-station-cadip-mps.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-mps.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-mps.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
    mti:
      service:
        name: cadip
        url: http://mockup-station-cadip-mti.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-mti.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-mti.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: openid
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: null
    nsg:
      service:
        name: cadip
        url: http://mockup-station-cadip-nsg.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-nsg.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-nsg.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: null
    sgs:
      service:
        name: cadip
        url: http://mockup-station-cadip-sgs.processing.svc.cluster.local:8080
      domain: mockup-station-cadip-sgs.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-station-cadip-sgs.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: null
    lta:
      service:
        name: lta
        url: http://mockup-lta-lta.processing.svc.cluster.local:8080
      domain: mockup-lta-lta.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-lta-lta.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
    s1a:
      service:
        name: prip
        url: http://mockup-prip-s1a.processing.svc.cluster.local:8080
      domain: mockup-prip-s1a.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-prip-s1a.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
    s2b:
      service:
        name: prip
        url: http://mockup-prip-s2b.processing.svc.cluster.local:8080
      domain: mockup-prip-s2b.processing.svc.cluster.local
      authentication:
        auth_type: oauth2
        token_url: http://mockup-prip-s2b.processing.svc.cluster.local:8080/oauth2/token
        grant_type: password
        scope: null
        username: test
        password: test
        client_id: client_id
        client_secret: client_secret
        authorization: Basic test
    cdse:
      service:
        name: s3
        url: https://eodata.dataspace.copernicus.eu
      domain: eodata.dataspace.copernicus.eu
      authentication:
        auth_type: s3
        access_key: example_s3_access_key
        secret_key: example_s3_secret_key
    s3test:
      domain: s3.gra.io.cloud.ovh.net
      service:
        name: s3
        url: https://s3.gra.io.cloud.ovh.net
      authentication:
        auth_type: s3
        access_key: ${access_key}
        secret_key: ${secret_key}
    pedc:
      service:
        name: edrs
        url: mockup-station-edrs-headless.processing.svc.cluster.local
        port: 21
      domain: mockup-station-edrs-headless.processing.svc.cluster.local
      authentication:
        auth_type: ftp
        username: 'test'
        password: 'test'
        ca_crt: |-
          -----BEGIN CERTIFICATE-----
          MIID...
          -----END CERTIFICATE-----

        client_crt: |-
          -----BEGIN CERTIFICATE-----
          MIID...
          -----END CERTIFICATE-----

        client_key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIID...
          -----END RSA PRIVATE KEY-----

    bedc:
      service:
        name: edrs
        url: mockup-station-edrs-headless.processing.svc.cluster.local
        port: 21
      domain: mockup-station-edrs-headless.processing.svc.cluster.local
      authentication:
        auth_type: ftp
        username: 'test'
        password: 'test'
        ca_crt: |-
          -----BEGIN CERTIFICATE-----
          MIID...
          -----END CERTIFICATE-----

        client_crt: |-
          -----BEGIN CERTIFICATE-----
          MIID...
          -----END CERTIFICATE-----

        client_key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIID...
          -----END RSA PRIVATE KEY-----
