# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
        type: {{ .Values.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Release.Name }}
        image: "{{ template "mychart.image" .Values.image }}"
        imagePullPolicy: {{ .Values.image.PullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.request.ram }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.ram }}
            cpu: {{ .Values.resources.limit.cpu }}
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.app.port }}
        env:
        - name: RSPY_UAC_CHECK_URL
          value: {{ .Values.app.uacUrl }}
        - name: RSPY_UAC_HOMEPAGE
          value: {{ .Values.app.uacHomeUrl }}
        - name: RSPY_DOCS_URL
          value: {{ .Values.app.docsUrl }}
        - name: STAC_BROWSER_URLS
          value: {{ .Values.stac-browser.urls }}
        securityContext:
          privileged: false
        {{ if .Values.probe }}
        {{ if .Values.probe.liveness }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.liveness.path }}
            port: {{ .Values.probe.liveness.port }}
          initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
        {{ end }}
        {{ if .Values.probe.readiness }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probe.readiness.path }}
            port: {{ .Values.probe.readiness.port }}
          initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
        {{ end }}
        {{ end }}
      {{ if .Values.image }}
      {{ if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      - name:  {{ .Values.image.imagePullSecrets }}
      {{ end }}
      {{ end }}
      restartPolicy: Always
      securityContext: {}
  revisionHistoryLimit: 10