kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.stationName }}
  namespace: {{ .Values.namespace }}
  generation: 1
  labels:
    app: {{ .Release.Name }}-{{ .Values.app.stationName }}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.stationName }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.app.stationName }}
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.stationName }}
        type: {{ .Values.namespace }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Release.Name }}-{{ .Values.app.stationName }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.PullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.request.ram }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.ram }}
            cpu: {{ .Values.resources.limit.cpu }}
        volumeMounts:
        - name: service-config-volume
          mountPath: {{ .Values.app.confDir }}/{{ .Values.app.authConfigFile }}
          subPath: {{ .Values.app.authConfigFile }}
        ports:
        - name: web
          protocol: TCP
          containerPort: {{ .Values.app.port }}
        securityContext:
          privileged: false
        #livenessProbe:
          #httpGet:
            #path: {{ .Values.probe.liveness.path }}
            #port: {{ .Values.probe.liveness.port }}
          #initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
          #periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          #timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
        #readinessProbe:
          #httpGet:
            #path: {{ .Values.probe.readiness.path }}
            #port: {{ .Values.probe.readiness.port }}
          #initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
          #periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          #timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
      #imagePullSecrets:
      #- name:  {{ .Values.image.imagePullSecrets }}
      restartPolicy: Always
      securityContext: {}
      volumes:
        - name: service-config-volume
          configMap:
            name: {{ .Release.Name }}-{{ .Values.app.stationName }}-service-config
  revisionHistoryLimit: 10