# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca-cert
  namespace: {{ .Values.namespace }}
  {{ if .Values.helmResourcePolicy }}
  annotations:
    helm.sh/resource-policy: {{ .Values.helmResourcePolicy }}
  {{ end }}
spec:
  isCA: true
  commonName: {{ .Release.Name }}
  secretName: {{ .Release.Name }}-ca-key-pair
  duration: 87600h # 10 years
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: {{ .Release.Name }}-selfsigned-issuer
    kind: Issuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-server-cert
  namespace: {{ .Values.namespace }}
  {{ if .Values.helmResourcePolicy }}
  annotations:
    helm.sh/resource-policy: {{ .Values.helmResourcePolicy }}
  {{ end }}
spec:
  secretName: {{ .Release.Name }}-server-tls
  duration: 8760h # 1 year
  renewBefore: 360h
  commonName: {{ .Release.Name }}
  dnsNames:
    - {{ .Release.Name }}
    - {{ .Release.Name }}-0
    - {{ .Release.Name }}-headless
    - {{ .Release.Name }}.{{ .Values.namespace }}.svc.cluster.local
    - {{ .Release.Name }}-0.{{ .Values.namespace }}.svc.cluster.local
    - {{ .Release.Name }}-headless.{{ .Values.namespace }}.svc.cluster.local
  usages:
    - server auth
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
    kind: Issuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-client-cert
  namespace: {{ .Values.namespace }}
  {{ if .Values.helmResourcePolicy }}
  annotations:
    helm.sh/resource-policy: {{ .Values.helmResourcePolicy }}
  {{ end }}
spec:
  secretName: {{ .Release.Name }}-client-tls
  duration: 8760h # 1 year
  renewBefore: 360h
  commonName: rs-server-edrs
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
    kind: Issuer