# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace for the deployment
namespace: processing

# -- Number of replicas for the deployment
replicaCount: 1

service:
  # -- Port for the service
  port: 8080

app:
  # -- Port for the application
  port: 5000
  # -- Working directory for the application
  workDir: /app
  # -- Config directory for the application
  confDir: /opt/lta/config
  # -- Auth configuration file for the application
  authConfigFile: auth.json
  # -- catalog configuration file for the application
  catalogConfigFile: GETQueryResponse.json

probe:
  liveness:
    # -- Path for the liveness probe
    path: /health
    # -- Port for the liveness probe
    port: 5000
    # -- InitialDelaySeconds for the liveness probe
    initialDelaySeconds: 30
    # -- periodSeconds for the liveness probe
    periodSeconds: 30
    # -- timeoutSeconds for the liveness probe
    timeoutSeconds: 5
  readiness:
    # -- Path for the readiness probe
    path: /health
    # -- Port for the readiness probe
    port: 5000
    # -- InitialDelaySeconds for the readiness probe
    initialDelaySeconds: 30
    # -- periodSeconds for the readiness probe
    periodSeconds: 30
    # -- timeoutSeconds for the readiness probe
    timeoutSeconds: 5

image:
  # -- Image registry
  registry: ghcr.io
  # -- Image repository
  repository: rs-python
  # -- Image name
  name: rs-testmeans_lta-station-mock
  # -- Image version, can be a tag or a digest
  version: sha256:47dc5b474865644e0f577008e21b498ddb4ed5143faabf15df238f1da5dcc3b4
  # -- Image pull policy
  PullPolicy: Always
  #imagePullSecrets: regcred

resources:
  request:
    # -- Pod memory request
    ram: "256Mi"
    # -- Pod CPU request
    cpu: "100m"
  limit:
    # -- Pod memory limit
    ram: "1000Mi"
    # -- Pod CPU limit
    cpu: "500m"

volume:
  # -- Size of the database volume
  size: "10Gi"
  # -- AccessMode of the database volume
  accessModes: ReadWriteOnce
  # -- StorageClass of the database volume
  storageClassName: csi-cinder-sc-retain

# -- Keep the ressources for PVC and ConfigMap. Default is to keep.
helmResourcePolicy: keep