# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace where to deploy the ConfigMap
namespace: processing

# -- Name to give to the configuration file
bucketConfigFileName: expiration_bucket.csv

# -- Bucket configuration
expiration_bucket_csv: |
  *, *, *, 30, rspython-ops-catalog-all-production
  copernicus, s1-l1, *, 10, rspython-ops-catalog-copernicus-s1-l1
  copernicus, s1-aux, *, 40, rspython-ops-catalog-copernicus-s1-aux
  copernicus, s1-aux, orbsct, 7300, rspython-ops-catalog-copernicus-s1-aux-infinite
  copernicus, s1-aux, obmemc, 7300, rspython-ops-catalog-copernicus-s1-aux-infinite
  copernicus, s3-l1-nrt, *, 10, rspython-ops-catalog-copernicus-s3-l1-nrt
  copernicus, s3-l1-ntc, *, 10, rspython-ops-catalog-copernicus-s3-l1-ntc
  copernicus, s3-l1-stc, *, 10, rspython-ops-catalog-copernicus-s3-l1-stc
  jules, *, *, 10, rspython-ops-catalog-jules-production
  jules, s2-l2, *, 30, rspython-ops-catalog-jules-s2-l2
  antoine, *, *, 60, rspython-ops-catalog-antoine-production
  antoine, *, TM_0_HKM___, 100, rspython-ops-catalog-antoine-s3-hkm
