apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.postgres.secret.user | b64enc | quote }}
  pass: {{ .Values.postgres.secret.pass | b64enc | quote }}