kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}-service
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}