# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mychart.Labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
  serviceName: {{ .Release.Name }}-headless
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: init-{{ .Release.Name }}
        image: alpine/curl
        command: [ "/scripts/init/{{ .Values.app.pgstac_init_download_schema_script }}" ]
        volumeMounts:
          - name: download-json-schema
            mountPath: /scripts/init/
          - name: pgstack-json-schema
            mountPath: /opt/pgstack_json_schema/
      containers:
      - name: {{ .Release.Name }}
        image: "{{ template "mychart.image" .Values.image }}"
        imagePullPolicy: {{ .Values.image.PullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.request.ram }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.ram }}
            cpu: {{ .Values.resources.limit.cpu }}
        ports:
        - name: web
          protocol: TCP
          containerPort: 5432
        volumeMounts:
          - name: pgstac-pgdata
            mountPath: /var/lib/postgresql/data
          - name: pgstack-json-schema
            mountPath: /opt/pgstack_json_schema/
          - name: patch-post-action
            mountPath: /docker-entrypoint-initdb.d/{{ .Values.app.pgstac_post_actions_script }}
            subPath: {{ .Values.app.pgstac_post_actions_script }}
        envFrom:
        - secretRef:
          name: {{ .Release.Name }}-postgres
        env:
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.port | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.host }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: PGDATABASE
          value: {{ .Values.postgres.db }}
        securityContext:
          privileged: false
        {{ if .Values.probe }}
        {{ if .Values.probe.startup }}
        startupProbe:
          exec:
            command:
              - pg_isready
              - -d
              - {{ .Values.postgres.db }}
          initialDelaySeconds: {{ .Values.probe.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.startup.timeoutSeconds }}
        {{ end }}
        {{ if .Values.probe.liveness }}
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -d
              - {{ .Values.postgres.db }}
          initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
        {{ end }}
        {{ if .Values.probe.readiness }}
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -d
              - {{ .Values.postgres.db }}
          initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
        {{ end }}
        {{ end }}
      restartPolicy: Always
      volumes:
        - name: download-json-schema
          configMap:
            name: {{ .Release.Name }}-download-json-schema
            defaultMode: 0744
        - name: patch-post-action
          configMap:
            name: {{ .Release.Name }}-patch-post-action
            defaultMode: 0744
        - name: pgstack-json-schema
          emptyDir: {}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: pgstac-pgdata
        annotations:
          helm.sh/resource-policy: {{ .Values.helmResourcePolicy }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.volume.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.volume.size }}
  revisionHistoryLimit: 10
