# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Run with watch"
description: "Run a command while watching pods"
inputs:
  namespace:
    required: true
  command:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        NAMESPACE="${{ inputs.namespace }}"
        CMD=$(echo "${{ inputs.command }}" | tr '\n' ' ')

        # Start watcher
        kubectl get pods -n "$NAMESPACE" -w &
        WATCH_PID=$!

        # Run command
        bash -c "$CMD" || INSTALL_STATUS=$?

        # Stop watcher
        kill $WATCH_PID || true

        # Exit properly
        exit ${INSTALL_STATUS:-0}
