# -- Namespace for the deployment
namespace: processing

# -- Number of replicas for the deployment
replicaCount: 1

service:
  # -- Port for the service
  port: 8080

app:
  # -- Port for the application
  port: 8000
  # -- URL of the API Key Manager service
  uacURL: http://apikeymanager.processing.svc.cluster.local:8000/check/api_key
  # -- Object Storage bucket for the catalog
  catalogBucket: rs-cluster-catalog

obs:
  # -- URL of the object storage service endpoint
  endpoint: http://minio.minio.svc.cluster.local:9000
  # -- Region of the object storage service
  region: sbg
  secret:
    # -- Access Key to authenticate with the object storage service
    ak: TDr8foJqSygBQ9YFmWDy
    # -- Secret Key to authenticate with the object storage service
    sk: z2RaqjFttnVZRTsLLqmy4PE6PzJOKzPsE47alDBs

postgres:
  # -- PostgreSQL port
  port: "5432"
  # -- PostgreSQL database name
  db: catalog
  host:
    # -- PostgreSQL service URL for Read Write
    rw: rs-server-catalog-db-svc.database.svc.cluster.local
    # -- PostgreSQL service URL for Read Only
    ro: rs-server-catalog-db-svc.database.svc.cluster.local
  secret:
    # -- Username to authenticate with the PostgreSQL service
    user: postgres
    # -- Password to authenticate with the PostgreSQL service
    pass: password

image:
  # -- Image registry
  registry: ghcr.io
  # -- Image repository
  repository: rs-python
  # -- Image name
  name: rs-server-catalog
  # -- Image version, can be a tag or a digest
  version: 0.1a8
  # -- Image pull policy
  PullPolicy: IfNotPresent
  #imagePullSecrets: regcred

ingress:
  issuer:
    # -- Ingress Issuer type
    type: cluster-issuer
    # -- Ingress Issuer name
    name: letsencrypt-prod
  # -- Ingress host name
  host: subdomain.example.com
  # -- Ingress path
  path: /catalog

resources:
  request:
    # -- Pod memory request
    ram: "256Mi"
    # -- Pod CPU request
    cpu: "100m"
  limit:
    # -- Pod memory limit
    ram: "1000Mi"
    # -- Pod CPU limit
    cpu: "500m"