namespace: processing

replicaCount: 1

service:
  port: 8080

app:
  port: 8000
  
probe:
  liveness:
    path: /health
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
  readiness:
    path: /health
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5

postgres:
  port: "5432"
  db: catalog
  host:
    rw: postgresql-cluster-rw.database.svc.cluster.local
    ro: postgresql-cluster-ro.database.svc.cluster.local
  secret:
    user: postgres
    pass: password

image:
  registry: ghcr.io
  repository: rs-python
  name: rs-server-catalog
  tag: auth
  PullPolicy: IfNotPresent
  #imagePullSecrets: regcred

ingress:
  issuer:
    type: cluster-issuer
    name: letsencrypt-prod
  host: subdomain.example.com
  path: /catalog

resources:
  request: 
    ram: "256Mi"
    cpu: "100m"
  limit:
    ram: "1000Mi"
    cpu: "500m"