# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.ingress }}
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/{{ .Values.ingress.issuer.type }}: {{ .Values.ingress.issuer.name }}
    nginx.ingress.kubernetes.io/cors-allow-headers: x-api-key, authorization
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{ range .Values.ingress.path }}
      - backend:
          service:
            name: {{ $.Release.Name }}-svc
            port:
              number: {{ $.Values.service.port }}
        path: {{ . | quote }}
        pathType: Prefix
      {{ end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host | replace "." "-" }}
{{ end }}
{{ end }}