apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/{{ .Values.ingress.issuer.type }}: {{ .Values.ingress.issuer.name }}
    nginx.ingress.kubernetes.io/cors-allow-headers: x-api-key
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host | replace "." "-" }}