apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.postgres.secret.user | b64enc | quote }}
  pass: {{ .Values.postgres.secret.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-obs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ak: {{ .Values.obs.secret.ak | b64enc | quote }}
  sk: {{ .Values.obs.secret.sk | b64enc | quote }}