# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.namespace }}
  
data:
  {{ .Values.app.pygeoapiConfig }}: |-
    server:
      url: http://localhost:8000
      bind:
        host: 0.0.0.0
        port: 8000
      admin: False
      languages:
        - en-US

    logging:
      level: DEBUG

    metadata:
      identification:
        title: RS-Staging Service
        description: A service to ingest external data as STAC items.
        keywords:
          - ogc
          - api
          - processes

    manager:
      name: TinyDB
      connection: /tmp/pygeoapi-process-manager.db
      output_dir: /tmp/

    resources:
      staging:
        type: process
        processor:
          name: RSPYStaging

    openapi:
      path: /docs/openapi.json

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-openapi
  namespace: {{ .Values.namespace }}
  
data:
  {{ .Values.app.openapiConfig }}: |-
    {
      "openapi": "3.0.2",
      "info": {
        "title": "RS-Staging Service API",
        "description": "API to ingest external data as STAC items",
        "version": "1.0.0",
        "contact": {
          "name": "Your Name",
          "email": "your.email@example.com"
        }
      },
      "servers": [
        {
          "url": "http://localhost:8000",
          "description": "Local Development Server"
        }
      ],
      "paths": {
        "/processes/staging/execution": {
          "post": {
            "summary": "Execute the staging process",
            "operationId": "executeStagingProcess",
            "requestBody": {
              "required": true,
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/ExecuteRequest"
                  }
                }
              }
            },
            "responses": {
              "200": {
                "description": "Successful execution",
                "content": {
                  "application/json": {
                    "schema": {
                      "$ref": "#/components/schemas/JobStatus"
                    }
                  }
                }
              }
            }
          }
        },
        "/jobs/{job_id}": {
          "get": {
            "summary": "Get job status by ID",
            "operationId": "getJobStatus",
            "parameters": [
              {
                "name": "job_id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "Successful response",
                "content": {
                  "application/json": {
                    "schema": {
                      "$ref": "#/components/schemas/JobStatus"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {
          "ExecuteRequest": {
            "type": "object",
            "properties": {
              "inputs": {
                "type": "object"
              }
            }
          },
          "JobStatus": {
            "type": "object",
            "properties": {
              "job_id": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "result": {
                "type": "object"
              }
            }
          }
        }
      }
    }