apiVersion: v1
appVersion: {{CHART_VERSION}}
description: RS SERVER CADIP
name: rs-server-cadip
version: {{CHART_VERSION}}
maintainers:
  - name: CS GROUP
    url: https://github.com/RS-PYTHON/rs-helm