apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.namespace }}
  
data:
  {{ .Values.app.eodagConfigFile }}: |-
    cadip:
      auth:
        type: GenericAuth
        method: basic
      products:
        GENERIC_PRODUCT_TYPE:
          productType: '{productType}'

      search:
        type: ODataV4Search
        api_endpoint: '{{ .Values.app.station.endpoint.url }}'
        need_auth: true
        results_entry: responses | $
        metadata_mapping:
            id:
                - null
                - '$.Id'
            Name:
                - null
                - '$.Name'
            SessionID:
                - null
                - '$.SessionID'
            Channel:
                - null
                - '$.Channel'
            BlockNumber:
                - null
                - '$.BlockNumber'
            FinalBlock:
                - null
                - '$.FinalBlock'
            PublicationDate:
                - null
                - '$.PublicationDate'
            EvictionDate:
                - null
                - '$.EvictionDate'
            Size:
                - null
                - '$.Size'
            Retransfer:
                - null
                - '$.Retransfer'
            # Eodag Specific map
            startTimeFromAscendingNode:
                - null
                - '$.PublicationDate'
            completionTimeFromAscendingNode:
                - null
                - '$.PublicationDate'
            geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
            downloadLink: '{{ .Values.app.station.endpoint.url }}({id})/$value'
            title: '$.Name'

        free_text_search_operations:
          $filter:
            union: ' OR '
            wrapper: '"{}"'
            operations:
                and:
                  - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
                  - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'

        pagination:
          max_items_per_page: 1000
          next_page_url_tpl: '{url}?{search}&$top={items_per_page}'
          total_items_nb_key_path: '$.total'

      download:
        type: HTTPDownload
        base_uri: '{{ .Values.app.station.endpoint.url }}'
        metadata_mapping:
            uid: '$.Id'
            downloadLink: '{{ .Values.app.station.endpoint.url }}({uid})/$value'
  {{ .Values.app.stationConfigFile }}: |-
    {
      "cadip": "{{ .Values.app.station.endpoint.url }}"
    }