# Copyright 2023-2025 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# THIS FILE WAS AUTOMATICALLY CREATED FROM:
#  - rs-server/services/cadip/config/cadip_search_config.template.yaml
#  - rs-server/services/cadip/config/cadip_ws_config.template.yaml
#  - rs-server/services/cadip/config/cadip_ws_config.template_session.yaml
#  - rs-server/resources/sync_config_files.py
# DON'T MODIFY IT DIRECTLY !

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.app.eodagConfigFile }}: |
    {{- range $k, $v := .Values.app.station }}
    {{ $.Files.Get (printf "config/%s" $v) | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-search-service-config
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.app.cadipSearchConfigFile }}: |
    {{ .Files.Get (printf "config/%s" .Values.app.cadipSearchConfigFile) | nindent 4 }}
