apiVersion: v1
appVersion: {{APP_VERSION}}
description: RS SERVER CATALOG DB
name: rs-server-catalog-db
version: {{CHART_VERSION}}
maintainers:
  - name: CS GROUP
    url: https://github.com/RS-PYTHON/rs-helm