namespace: database

service:
  port: 5432

postgres:
  port: "5432"
  db: catalog
  host: catalog-db.database.svc.cluster.local
  secret:
    user: postgres
    pass: password

image:
  registry: ghcr.io
  repository: stac-utils
  name: pgstac
  tag: v0.7.10
  PullPolicy: IfNotPresent

resources:
  request: 
    ram: "256Mi"
    cpu: "100m"
  limit:
    ram: "1000Mi"
    cpu: "500m"

volume:
  size: "20Gi"
  accessModes: ReadWriteOnce
  storageClassName: csi-cinder-sc-retain