# -- Namespace for the deployment
namespace: database

service:
  # -- Port for the service
  port: 5432

postgres:
  # -- PostgreSQL port
  port: "5432"
  # -- PostgreSQL database name
  db: catalog
  secret:
    # -- Username to authenticate with the PostgreSQL service
    user: postgres
    # -- Password to authenticate with the PostgreSQL service
    pass: password

image:
  # -- Image registry
  registry: ghcr.io
  # -- Image repository
  repository: stac-utils
  # -- Image name
  name: pgstac
  # -- Image version, can be a tag or a digest
  version: v0.7.10
  # -- Image pull policy
  PullPolicy: IfNotPresent
  
resources:
  request:
    # -- Pod memory request
    ram: "256Mi"
    # -- Pod CPU request
    cpu: "100m"
  limit:
    # -- Pod memory limit
    ram: "1000Mi"
    # -- Pod CPU limit
    cpu: "500m"

volume:
  # -- Size of the database volume
  size: "20Gi"
  # -- AccessMode of the database volume
  accessModes: ReadWriteOnce
  # -- StorageClass of the database volume
  storageClassName: csi-cinder-sc-retain