apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.namespace }}
  
data:
  {{ .Values.app.eodagConfigFile }}: |-
    ADGS:
      auth:
        type: GenericAuth
        method: basic
        credentials:
            username: {{ .Values.app.station.endpoint.secret.username }}
            password: {{ .Values.app.station.endpoint.secret.password }}
      products:
        GENERIC_PRODUCT_TYPE:
          productType: '{productType}'

      search:
        type: ODataV4Search
        api_endpoint: '{{ .Values.app.station.endpoint.url }}'
        need_auth: true
        results_entry: responses | $
        metadata_mapping:
            id:
                - null
                - '$.Id'
            Name:
              - null
              - '$.Name'
            ContentLength:
              - null
              - '$.ContentLength'
            PublicationDate:
              - null
              - '$.PublicationDate'
            Start:
              - null
              - '$.ContentDate.Start'
            End:
              - null
              - '$.ContentDate.End'
            startTimeFromAscendingNode:
                - null
                - '$.PublicationDate'
            completionTimeFromAscendingNode:
                - null
                - '$.PublicationDate'
            geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
            downloadLink: '{{ .Values.app.station.endpoint.url }}({id})/$value'
            title: '$.Name'

        free_text_search_operations:
          $filter:
            union: ' OR '
            wrapper: '"{}"'
            operations:
                and:
                  - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
                  - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'

        pagination:
          max_items_per_page: 1000
          next_page_url_tpl: '{url}?{search}&$top={items_per_page}'
          total_items_nb_key_path: '$.total'

      download:
        type: HTTPDownload
        base_uri: '{{ .Values.app.station.endpoint.url }}'
        metadata_mapping:
            uid: '$.Id'
            downloadLink: '{{ .Values.app.station.endpoint.url }}({uid})/$value'
  {{ .Values.app.stationConfigFile }}: -|
    {
      "ADGS": "{{ .Values.app.station.endpoint.url }}"
    }