# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
  namespace: {{ .Values.namespace }}
  
data:
  {{ .Values.app.eodagConfigFile }}: |-
    {{- range $k, $v := .Values.app.station }}
      {{ $k }}:
        auth:
          type: TokenAuth
          auth_uri: '{{ $v.endpoint.url }}/oauth2/token'
          token_type: json
          token_key: access_token
          request_method: POST        
        products:
          CAMS_GRF_AUX:
            productType: cams-ads-grf-aux

        search:
          type: ODataV4Search
          api_endpoint: '{{ $v.endpoint.url }}'
          need_auth: true
          results_entry: responses | $
          metadata_mapping:
              id:
                  - null
                  - '$.Id'
              Name:
                - null
                - '$.Name'
              ContentLength:
                - null
                - '$.ContentLength'
               ContentType:
                - null
                - '$.ContentType'
              PublicationDate:
                - null
                - '$.PublicationDate'
              EvictionDate:
                - null
                - '$.EvictionDate'
              Start:
                - null
                - '$.ContentDate.Start'
              End:
                - null
                - '$.ContentDate.End'
              startTimeFromAscendingNode:
                  - null
                  - '$.PublicationDate'
              completionTimeFromAscendingNode:
                  - null
                  - '$.PublicationDate'      
              ChecksumValue:
                - null
                - '$.Checksum[0].Value'
              attr_ptype:
                  - null
                  - '$.attr_ptype'
              attr_serial_identif:
                  - null
                  - '$.attr_serial_identif'
              attr_platform_short_name:
                  - null
                  - '$.attr_platform_short_name'
              attr_processing_date:
                  - null
                  - '$.attr_processing_date'
              attrs:
                  - null
                  - '$.Attributes'
              geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
              downloadLink: '{{ $v.endpoint.url }}({id})/$value'
              title: '$.Name'

          free_text_search_operations:
            $filter:
              union: ' OR '
              wrapper: '"{}"'
              operations:
                  and:
                    - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
                    - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'
                    - "Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq '{attr_ptype}')"
                    - "Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformSerialIdentifier' and att/OData.CSC.StringAttribute/Value eq '{attr_serial_identif}')"
                    - "Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'platformShortName' and att/OData.CSC.StringAttribute/Value eq '{attr_platform_short_name}')"
                    - "Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'processingDate' and att/OData.CSC.StringAttribute/Value eq '{attr_processing_date#to_iso_utc_datetime}')"
          pagination:
            max_items_per_page: 1000
            next_page_url_tpl: '{url}?{search}&$top={items_per_page}&$expand=Attributes'
            total_items_nb_key_path: '$.total'

        download:
          type: HTTPDownload
          base_uri: '{{ $v.endpoint.url }}'
          metadata_mapping:
              uid: '$.Id'
              downloadLink: '{{ $v.endpoint.url }}({uid})/$value'
    {{- end }}
  {{ .Values.app.eodagConfigFileTokenModule }}: |-
    {{- range $k, $v := .Values.app.station }}
      {{ $k }}:
        auth:
          type: HTTPHeaderAuth
          headers:
              Authorization: "Bearer {token}"
          credentials:
            token: token_value
        products:
          CAMS_GRF_AUX:
            productType: cams-ads-grf-aux

        search:
          type: ODataV4Search
          api_endpoint: '{{ $v.endpoint.url }}'
          need_auth: true
          results_entry: responses | $
          metadata_mapping:
              id:
                  - null
                  - '$.Id'
              Name:
                - null
                - '$.Name'
              ContentLength:
                - null
                - '$.ContentLength'
              PublicationDate:
                - null
                - '$.PublicationDate'
              Start:
                - null
                - '$.ContentDate.Start'
              End:
                - null
                - '$.ContentDate.End'
              startTimeFromAscendingNode:
                  - null
                  - '$.PublicationDate'
              completionTimeFromAscendingNode:
                  - null
                  - '$.PublicationDate'
              geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
              downloadLink: '{{ $v.endpoint.url }}({id})/$value'
              title: '$.Name'

          free_text_search_operations:
            $filter:
              union: ' OR '
              wrapper: '"{}"'
              operations:
                  and:
                    - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
                    - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'

          pagination:
            max_items_per_page: 1000
            next_page_url_tpl: '{url}?{search}&$top={items_per_page}'
            total_items_nb_key_path: '$.total'

        download:
          type: HTTPDownload
          base_uri: '{{ $v.endpoint.url }}'
          metadata_mapping:
              uid: '$.Id'
              downloadLink: '{{ $v.endpoint.url }}({uid})/$value'
    {{- end }}
  {{ .Values.app.stationConfigFile }}: |-
    {
      {{- range $k, $v := .Values.app.station }}
      "{{ $k }}": "{{ $v.endpoint.url }}"
      {{- end }}
    }

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-search-service-config
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.app.cadipSearchConfigFile }}: |-
  collections:
  - id: s1_adgs_OPER_AUX_ECMWFD_PDMC
    station: adgs
    query:
      productType: OPER_AUX_ECMWFD_PDMC
    stac_extensions: [ "https://stac-extensions.github.io/eo/v1.0.0/schema.json", "https://stac-extensions.github.io/projection/v1.0.0/schema.json", "https://stac-extensions.github.io/view/v1.0.0/schema.json" ]
    title: 'Sentinel-1 Inuvik CADIP sessions'
    description: 'Sentinel-1 Inuvik CADIP sessions'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://scihub.copernicus.eu/twiki/pub/SciHubWebPortal/TermsConditions/Sentinel_Data_Terms_and_Conditions.pdf'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/s1-mission'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'

  - id: s2_adgs2_AUX_OBMEMC
    station: adgs2
    query:
      productType: AUX_OBMEMC
    stac_extensions: [ "https://stac-extensions.github.io/eo/v1.0.0/schema.json", "https://stac-extensions.github.io/projection/v1.0.0/schema.json", "https://stac-extensions.github.io/view/v1.0.0/schema.json" ]
    title: 'Sentinel-1 Inuvik CADIP sessions'
    description: 'Sentinel-1 Inuvik CADIP sessions'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://scihub.copernicus.eu/twiki/pub/SciHubWebPortal/TermsConditions/Sentinel_Data_Terms_and_Conditions.pdf'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/s1-mission'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'

  - id: aux_interval
    station: adgs
    query:
      PublicationDate: 2023-01-01T12:00:00Z/2024-01-01T12:00:00Z
    stac_extensions: [ "https://stac-extensions.github.io/eo/v1.0.0/schema.json", "https://stac-extensions.github.io/projection/v1.0.0/schema.json", "https://stac-extensions.github.io/view/v1.0.0/schema.json" ]
    title: 'Sentinel-1 Inuvik CADIP sessions'
    description: 'Sentinel-1 Inuvik CADIP sessions'
    license: other
    extent:
      spatial:
        bbox: [[ -180, -82.85, 180, 82.82 ]]
      temporal:
        interval: [[ '2024-06-12T02:57:21.459000Z', '2024-08-22T11:30:12.767000Z' ]]
    links:
      - rel: license
        href: 'https://scihub.copernicus.eu/twiki/pub/SciHubWebPortal/TermsConditions/Sentinel_Data_Terms_and_Conditions.pdf'
        title: 'Legal notice on the use of Copernicus Sentinel Data and Service Information'
    providers:
      - name: 'European Union/ESA/Copernicus'
        roles:
          - producer
          - licensor
        url: 'https://sentiwiki.copernicus.eu/web/s1-mission'
      - name: 'Reference System'
        roles:
          - host
        url: 'https://home.rs-python.eu/'
