# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.postgres.secret.user | b64enc | quote }}
  pass: {{ .Values.postgres.secret.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-obs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ak: {{ .Values.obs.secret.ak | b64enc | quote }}
  sk: {{ .Values.obs.secret.sk | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-endpoint
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.app.station.endpoint.secret.username | b64enc | quote }}
  pass: {{ .Values.app.station.endpoint.secret.username | b64enc | quote }}