apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.postgres.secret.user }}
  pass: {{ .Values.postgres.secret.pass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-obs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ak: {{ .Values.obs.secret.ak }}
  sk: {{ .Values.obs.secret.sk }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-endpoint
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.app.station.endpoint.secret.username }}
  pass: {{ .Values.app.station.endpoint.secret.username }}