# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality

on:
  push:
    branches:
      - develop  # pushes on the 'develop' branch
    tags:
      - '**'  # new git tags (including hierarchical tags like v1.0/beta)
  pull_request:
    types: [opened, synchronize, reopened]
    # run this worflow only for code/test related changes (avoid it for documentation)
    paths: ['**.json', '**.lock', '**.py', '**.raw', '**.sh', '**.toml', '**.yaml', '**.yml']
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.12

jobs:

  check-format:
    runs-on: ubuntu-latest
    name: Check pre-commit
    steps:
      - uses: actions/checkout@v6
      - run: >
          echo
          ":information_source: This job checks that you have run \`pre-commit run --all-files\` in
          your local git repository before committing."
          >> $GITHUB_STEP_SUMMARY
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd

  generate-quality-report:
    runs-on: ubuntu-latest
    name: Quality report (sonarqube)
    permissions:
      pull-requests: write  # for: phwt/sonarqube-quality-gate-action
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: RS-PYTHON_rs-helm
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Full history for SCM and branch analysis

      - name: Run SonarCloud Scanner
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=rs-python
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.version=${{ env.PYTHON_VERSION }}
            -Dsonar.python.bandit.reportPaths=./bandit-report.json

      - name: Wait for quality gate result
        run: sleep 5

      - name: Report quality gate result in the pull request comment
        uses: phwt/sonarqube-quality-gate-action@e8842ff65b97bfa4fd4effe3ab0909f568d16e91
        id: quality-gate-result
        with:
          sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-token: ${{ env.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Output result
        run: |
          echo "Project status: ${{ steps.quality-gate-result.outputs.project-status }}"
          echo "Quality gate result: ${{ steps.quality-gate-result.outputs.quality-gate-result }}"

      - id: check-gate
        name: Check quality gate status
        uses: sonarsource/sonarqube-quality-gate-action@cb3ed20f9fec62b4c3b8ad9e77656c6adaade913
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
