name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the rs-server version tag
        id: get_version
        uses: ./.github/actions/get_version

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2
        with:
          yamale_version: "6.0.0"

      - name: List changed Chart.yaml and update version number
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "$changed"
            echo "changed=true" >> "$GITHUB_OUTPUT"
            for dir in $changed; do
              sed -i -e "s,{{APP_VERSION}},${{ steps.get_version.outputs.APP_VERSION }}," \
                     -e "s,{{CHART_VERSION}},${{ steps.get_version.outputs.CHART_VERSION }}," \
                     "$dir/Chart.yaml"
            done
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Create required namespace
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl create namespace processing

      - name: Run chart-testing (install)
        if: false  # This step is disabled for now, needs a lot more work to be functional
        run: ct install --debug --namespace processing --target-branch ${{ github.event.repository.default_branch }}
